# Generated by Django 5.1.6 on 2025-02-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Média'), ('B', 'Baixa')], default='M', max_length=1),
        ),
    ]
