# Generated by Django 5.1.6 on 2025-02-13 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthtask',
            name='semana',
        ),
        migrations.RemoveField(
            model_name='weektask',
            name='dia',
        ),
        migrations.AddField(
            model_name='dailytask',
            name='semana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.weektask'),
        ),
        migrations.AddField(
            model_name='weektask',
            name='mes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.monthtask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('L', 'Lembrete'), ('E', 'Evento'), ('N', 'Nota'), ('M', 'Meta')], default='L', max_length=1),
        ),
    ]
