# Generated by Django 5.1.6 on 2025-02-13 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_monthtask_semana_remove_weektask_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='semana',
        ),
        migrations.RemoveField(
            model_name='weektask',
            name='mes',
        ),
        migrations.AddField(
            model_name='monthtask',
            name='semana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.weektask'),
        ),
        migrations.AddField(
            model_name='weektask',
            name='dia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.dailytask'),
        ),
        migrations.AlterField(
            model_name='monthtask',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='weektask',
            name='tarefa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='weektask',
            name='week',
            field=models.CharField(blank=True, choices=[('1', 'Primeira Semana'), ('2', 'Segunda Semana'), ('3', 'Terceira Semana'), ('4', 'Quarta Semana')], max_length=1, null=True),
        ),
    ]
