# Generated by Django 5.1.6 on 2025-02-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_dailytask_semana_remove_weektask_mes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('D', 'Dia'), ('S', 'Semana'), ('M', 'Mes')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='weektask',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='monthtask',
            name='semana',
        ),
        migrations.RemoveField(
            model_name='monthtask',
            name='tarefa',
        ),
        migrations.RemoveField(
            model_name='weektask',
            name='tarefa',
        ),
        migrations.DeleteModel(
            name='DailyTask',
        ),
        migrations.DeleteModel(
            name='MonthTask',
        ),
        migrations.DeleteModel(
            name='WeekTask',
        ),
    ]
