# Generated by Django 5.1.6 on 2025-02-13 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_timetask_remove_weektask_dia_remove_monthtask_semana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetask',
            name='day',
            field=models.CharField(blank=True, choices=[('SEG', 'Segunda'), ('TER', 'Terça'), ('QUA', 'Quarta'), ('QUI', 'Quinta'), ('SEX', 'Sexta'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='timetask',
            name='month',
            field=models.CharField(blank=True, choices=[('JAN', 'Janeiro'), ('FEV', 'Fevereiro'), ('MAR', 'Março'), ('ABR', 'Abril'), ('MAI', 'Maio'), ('JUN', 'Junho')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='timetask',
            name='tarefa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetask',
            name='week',
            field=models.CharField(blank=True, choices=[('1', 'Primeira Semana'), ('2', 'Segunda Semana'), ('3', 'Terceira Semana'), ('4', 'Quarta Semana')], max_length=1, null=True),
        ),
    ]
