# Generated by Django 5.1.6 on 2025-02-13 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_timetask_day_timetask_month_timetask_tarefa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
    ]
